name: CD
on:
  push:
    branches:
      - main
      - backport/*.*
    paths:
      - config/**
      - spack.yaml
jobs:
  cd:
    name: CD
    uses: access-nri/build-cd/.github/workflows/cd.yml@v6
    with:
      model: ${{ vars.NAME }}
      # TODO: Check versions are appropriate
      spack-manifest-schema-version: 1-0-7
      config-versions-schema-version: 3-0-0
      config-packages-schema-version: 1-0-0
    permissions:
      contents: write
      # This is due to the entrypoint also handling `on.pull_request` events
      pull-requests: write
    secrets: inherit
