name: CD
on:
  push:
    branches:
      - main
      - backport/*.*
    paths:
      - config/**
      - spack.yaml
jobs:
  cd:
    name: CD
    uses: access-nri/build-cd/.github/workflows/cd.yml@v6
    with:
      model: ${{ vars.NAME }}
      # TODO: Get versions of applicable schema from ACCESS-NRI/schema
      spack-manifest-schema-version: SET_SCHEMA_VERSION_HERE
      config-versions-schema-version: SET_SCHEMA_VERSION_HERE
      config-packages-schema-version: SET_SCHEMA_VERSION_HERE
    permissions:
      contents: write
      # This is due to the entrypoint also handling `on.pull_request` events
      pull-requests: write
    secrets: inherit
